export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const SIGN_OUT = 'SIGN_OUT'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ADD_QUESTIONS = 'ADD_QUESTIONS'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'

export const RECEIVE_USERS = 'RECEIVE_USERS'